language: generic
sudo: required

service:
  - docker
  
before-install:
    - docker build -t prafullpol/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true prafullpol/docker-react npm run test -- --coverage
