sudo: required
language: generic

service:
  - docker
  
#before-install:
 #   - docker build -t prafullpol/docker-react -f Dockerfile.dev .
    
#script:
#  - docker run prafullpol/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-926990747009"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
